### PR TITLE
Update logical definitions to correct unsatisfiable classes

### PR DESCRIPTION
**Pull request by balhoff**
Hi, here are some changes I'd like to propose to fix a bunch of unsatisfiable classes in MP. You can view the differences at this link:

https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fmammalian-phenotype-ontology%2Fraw%2F76444d629dc7d4af4c31289f5c7f322a2095e62b%2Fsrc%2Fontology%2Fmp-edit.owl&right=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fmammalian-phenotype-ontology%2Fraw%2Foccurs-in%2Fsrc%2Fontology%2Fmp-edit.owl&loadimports=true

One of the definitions uses ['results in development of'](http://purl.obolibrary.org/obo/RO_0002296), which I'm trying to add to the Upheno ro_import (once I figure out how that works)—so it doesn't have a label at the moment.

### CODE REVIEW

**Comment by sbello** [comment]
These changes conflict with the established YAML patterns, see https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemicalInEntity for example. @cmungall @nicolevasilevsky @cindyJax Do we want to change the patterns to use 'occurs in' rather than 'part of'?

**Comment by balhoff** [comment]
Those patterns will work with 'part of' since they're restricted to changes in amount of chemical entities. We may want to make some additional patterns using 'occurs in' for use with processes/occurrents to make this more consistent.

**Comment by sbello** [comment]
Ah, I see now. I think it was this example that threw me:
abnormal urine enzyme level - http://purl.obolibrary.org/obo/MP_0001760
Removed:  abnormal urine enzyme level EquivalentTo has part some (amount and (inheres in some (catalytic activity and (part of some urine))) and (has modifier some abnormal))

Added: abnormal urine enzyme level EquivalentTo has part some (amount and (inheres in some (catalytic activity and (occurs in some urine))) and (has modifier some abnormal))

Possibly the issue is using 'catalytic activity' = enzyme in the axioms. The text definition is 'any change in the level of enzymes in the urine'. Basically this is the level of a type of protein that has a specific function (enzyme) in the urine. This seems to be to be similar to other chemical entities.

**Comment by balhoff** [comment]
I see, yes there might be a different formulation possible for that one. I was trying not to change the content of the definitions more than was needed to make the logic happy.

**Comment by sbello** [comment]
Created issue #2534 to remind me to review the logical definition of MP:0001760.

**Pull request merged**
