### PR TITLE
Change weight to mass

### PR DESCRIPTION
**Pull request by matentzn**
Example change:

image

### CODE REVIEW

**Comment by matentzn** [comment]
See https://github.com/obophenotype/bio-attribute-ontology/issues/39

**Comment by sbello** [comment]
Some terms have eq with both weight and decreased/increased weight (see http://purl.obolibrary.org/obo/MP_0009674) Before I approve and merge I want to check with Nico that changing just one won't break anything. We will still need to fix these and any increased/decreased weight terms with simpler eqs.

**Comment by matentzn** [comment]
Very good point! Can you send a message to Nicole about that?

**Comment by sbello** [comment]
Messaged Nicole on slack.

**Comment by sbello** [comment]
Nicole has already changed all the various weight terms. I'll approve this and keep my fingers crossed that the half-changed eqs don't cause anything to choke.

**Pull request merged**
