### PR TITLE
Changed makefile to use java commands

### PR DESCRIPTION
**Pull request by oblodgett**

### CODE REVIEW

**Comment by cmungall** [comment]
Seems OK to merge. Is this for @sbello to run locally or for running as part of JAX pipeline?

**Comment by sbello** [comment]
Yes, @cmungall Olin is working on adapting the files you provided to work on my machine as I can't run Docker. This is waiting for Olin to tell me he's ready for me to merge.

**Comment by matentzn** [comment]
This is going to be obsolete quite soon. Can I close this without merging?

**Comment by oblodgett** [comment]
Sure thats fine... I'll close it.

**Pull request closed without merging**
